### ISSUE TITLE
hap y bi dd ay

### ISSUE THREAD

**Issue by whomistenshi** [TheUndscr/Dis2Rob.py#1]
Hellompls fix c this bucg dfeveloppr per!!!! Pls i have a wi fe and 2 kids this is devastating

**Comment by TheUndscr** [comment]
ok send location

**Comment by TheUndscr** [comment]
for free repaior and

**Comment by whomistenshi** [comment]
> ok send location

34°42'03.3"N 135°49'16.6"E

**Comment by TheUndscr** [comment]
than k you i will come in 2 yeard please stay

**Comment by whomistenshi** [comment]
:D

**Comment by TheUndscr** [comment]
> :D

i bought ticket for flight i will comed in 2 week
